### ISSUE TITLE
Enrich useAction with multiple picker.

### ISSUE THREAD

**Issue by apostolidhs** [novykh/react-hoax#5]
There are many cases in a project that we need many actions in one component. E.g.

```
  const startFetch = useJobAction('startFetch');
  const doneFetch = useJobAction('doneFetch');
  const failFetch = useJobAction('failFetch');
```

Consider adding either an array as selector (preferred)

`const [startFetch, doneFetch, failFetch] = useJobAction(['startFetch', 'doneFetch', 'failFetch']);`

or an additional multiple action selection function.

`const [startFetch, doneFetch, failFetch] = useJobActions(['startFetch', 'doneFetch', 'failFetch']);`

**Comment by novykh** [comment]
Is this really needed? You can always destruct the plain `const {action1, ... , actionN} = useAction()` result.

**Comment by apostolidhs** [comment]
You are right, we could take that choice as well.

**Comment by novykh** [comment]
Fixed.
